server:
  port: 8081

spring:
  application:
    name: 'customer-service'

  jackson:
    serialization:
      indent_output: true
    default-property-inclusion: non_null

  datasource:
    driver-class-name: org.postgresql.Driver
    name: customer_service
    password: customer_service_admin
    username: customer_service_admin
    url: jdbc:postgresql://localhost:5432/${spring.datasource.name}

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: false
        format_sql: true

    open-in-view: false

  kafka:
    bootstrap-servers: localhost:9092