POST localhost:8080/order
Content-Type: application/json

{
  "customerId": 15,
  "orderItems": [
    {
      "price": 350,
      "name": "Another flight ticket to somewhere else"
    },
    {
      "price": 250,
      "name": "Another hotel ticket somewhere else 2"
    }
  ]
}